### ISSUE TITLE
Data and data-details page too long to load

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/riskdatalibrary.org#89]
Not a priority but need to investigate issue.

**Comment by MamadioCMCC** [comment]
Very much likely related to the huge size of the DB.
See other issue: https://github.com/GFDRR/rdl-infra/issues/44
We'll investigate more.

**Comment by ConnectedSystems** [comment]
Quite possibly @MamadioCMCC . There could also be DB performance tweaks that would resolve it.

For demonstration purposes, might be easier to link to a stored file rather than a DB generated file. Solutions depend on whether I can get access to the Amazon-hosted code (via DiUS I presume).

In any case I plan to do some load testing to investigate tonight (your morning).

**Comment by ConnectedSystems** [comment]
@pzwsk when you say "too long to load", how long would you describe the load time? 5-10 seconds?

I tested with a website load tester, simulating 250 users, with some of those users downloading a data set. I got the occasional error, yes (but I think that can be addressed by tuning the database a bit).

While the above was running, I manually used the website and while the page did sometimes feel "slow" it wasn't unbearable. The data details page would load in ~5 seconds. Not instant, yes, but manageable.

![image](https://user-images.githubusercontent.com/4075136/100429782-ef958980-30e9-11eb-90b1-7ed1f8ca4aaf.png)
